language: node_js
node_js:
- '4.0'
env:
  global:
  - GH_REF: github.com/anandthakker/anandthakker.github.io
  - secure: e1BJeEJDGE81b0JGF6Agjb9iSKgiVo1Hn6GkRRlmvM1jMt9+9Acwbo5Pm3rtd/M8k0FC2thPFpMMTjvqmAVGKdUw3kCE5K6AdgHUqkArKeREULHfqD0YdERHDoeHa8Xi6dcbk00inkyjxYBq4dQwZVnU5zFyybt3cfvWMaORxhU=
before_install: gem install sass
script: npm run build
deploy:
  provider: script
  script: deploy.sh
  on:
    branch: content
